#!/usr/bin/env node
/**
 * Idempotent patch for src-tauri/gen/android/app/src/main/AndroidManifest.xml.
 *
 * Tauri 2 doesn't (yet) expose intent-filters or arbitrary manifest entries
 * via tauri.conf.json, and `gen/android/` is regenerated by `tauri android init`,
 * so we keep the customizations as a script that re-applies them on demand.
 *
 * Run automatically by `npm run android:init` and `npm run android:patch`.
 * Idempotent: running twice is a no-op.
 */
import { readFile, writeFile, access } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const MANIFEST = resolve(
  ROOT,
  "src-tauri/gen/android/app/src/main/AndroidManifest.xml"
);
const MAIN_ACTIVITY = resolve(
  ROOT,
  "src-tauri/gen/android/app/src/main/java/app/linkvault/desktop/MainActivity.kt"
);
const MAIN_ACTIVITY_SOURCE = resolve(ROOT, "scripts/android-mainactivity.kt");

async function exists(path) {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

const CAMERA_PERMISSION = `<uses-permission android:name="android.permission.CAMERA" />`;
const CAMERA_FEATURE = `<uses-feature android:name="android.hardware.camera" android:required="false" />`;

const SHARE_TEXT_FILTER = `<intent-filter>
                <action android:name="android.intent.action.SEND" />
                <category android:name="android.intent.category.DEFAULT" />
                <data android:mimeType="text/plain" />
            </intent-filter>`;

const SHARE_AUDIO_FILTER = `<intent-filter>
                <action android:name="android.intent.action.SEND" />
                <category android:name="android.intent.category.DEFAULT" />
                <data android:mimeType="audio/*" />
            </intent-filter>`;

function ensureCameraPermission(xml) {
  if (xml.includes("android.permission.CAMERA")) return { xml, changed: false };
  const next = xml.replace(
    /(<uses-permission android:name="android\.permission\.INTERNET" \/>)/,
    `$1\n    ${CAMERA_PERMISSION}\n    ${CAMERA_FEATURE}`
  );
  return { xml: next, changed: next !== xml };
}

function ensureShareIntent(xml, mime, snippet) {
  // Detect by checking for the data tag with the specific mimeType inside an
  // intent-filter that uses SEND.
  const probe = new RegExp(
    `<intent-filter>[\\s\\S]*?android\\.intent\\.action\\.SEND[\\s\\S]*?android:mimeType="${mime.replace(
      "*",
      "\\*"
    )}"[\\s\\S]*?</intent-filter>`
  );
  if (probe.test(xml)) return { xml, changed: false };

  // Inject right after the LAUNCHER intent-filter inside MainActivity.
  const next = xml.replace(
    /(<intent-filter>\s*<action android:name="android\.intent\.action\.MAIN" \/>[\s\S]*?<\/intent-filter>)/,
    `$1\n\n            ${snippet}`
  );
  if (next === xml) {
    throw new Error(
      "Could not find LAUNCHER intent-filter to anchor the SEND filter on. Was the manifest layout changed?"
    );
  }
  return { xml: next, changed: true };
}

async function main() {
  if (!(await exists(MANIFEST))) {
    console.error(
      `error: ${MANIFEST} not found. Run \`npm run tauri -- android init\` first.`
    );
    process.exit(1);
  }

  const original = await readFile(MANIFEST, "utf8");
  let xml = original;
  const log = [];

  let r = ensureCameraPermission(xml);
  xml = r.xml;
  if (r.changed) log.push("✓ added CAMERA permission + uses-feature");

  r = ensureShareIntent(xml, "text/plain", SHARE_TEXT_FILTER);
  xml = r.xml;
  if (r.changed) log.push("✓ added SEND text/plain intent-filter");

  r = ensureShareIntent(xml, "audio/*", SHARE_AUDIO_FILTER);
  xml = r.xml;
  if (r.changed) log.push("✓ added SEND audio/* intent-filter");

  if (xml !== original) {
    await writeFile(MANIFEST, xml, "utf8");
    for (const line of log) console.log(line);
    console.log(`Patched: ${MANIFEST}`);
  } else {
    console.log("AndroidManifest.xml already patched.");
  }

  // Replace MainActivity.kt with our version (Share Intent handler).
  if (await exists(MAIN_ACTIVITY)) {
    const desired = await readFile(MAIN_ACTIVITY_SOURCE, "utf8");
    const current = await readFile(MAIN_ACTIVITY, "utf8");
    if (current.trim() !== desired.trim()) {
      await writeFile(MAIN_ACTIVITY, desired, "utf8");
      console.log(`✓ replaced MainActivity.kt with Share Intent handler`);
    } else {
      console.log("MainActivity.kt already up to date.");
    }
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
